//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kapa
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public string OrderCount { get; set; }
        public string OrderStatus { get; set; }
        public string OrderDate { get; set; }
        public string OrderDeliveryDate { get; set; }
        public string OrderPickupPoint { get; set; }
        public string ClientFullName { get; set; }
        public string CodeToGet { get; set; }
    
        public virtual OrderProduct OrderProduct { get; set; }
    }
}
